version: "3"
services:
  kookbang-friends-sample-client:
    restart: always
    container_name: kookbang-friends-sample-client
    image: kookbang-friends-sample-client
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - ./client/:/app
    ports:
      - "3000:3000"
    networks:
      - backend

  # kookbang-friends-sample-dev:
  #   restart: always
  #   container_name: kookbang-friends-sample-dev
  #   image: kookbang-friends-sample-dev
  #   build:
  #     dockerfile: Dockerfile.dev
  #     context: ./dev
  #   volumes:
  #     - ./dev/:/app
  #   ports:
  #     - "3001:3000"
  #   networks:
  #     - backend

  strapi:
    container_name: kookbang-friends-sample-api
    image: strapi/strapi
    environment:
      - DATABASE_CLIENT=mongo
      - DATABASE_HOST=db
      - DATABASE_PORT=27017
      - DATABASE_NAME=kookbangfriendssample
    ports:
      - 1337:1337
    volumes:
      - ./api:/srv/app
    restart: always
    depends_on:
      - db
    networks:
      - backend

  db:
    container_name: kookbang-friends-sample-db
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=kookbangfriendssample
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
      - ./mongodb/mongod.conf:/etc/mongod.conf
    restart: always
    networks:
      - backend
    command: ["-f", "/etc/mongod.conf"]

networks:
  backend:
    driver: bridge
